gpu-stats-collector: 
  ingress:
    enabled: false


gpu_stats_collector:
  ingress_path: /gpu/metrics
  port: 80

kube_state_metrics:
  ingress_path: /
  port: 80

kube-state-metrics:
  service:
    port: 80
    



