apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ets-metrics-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - ets-metrics.ucsd.edu
    secretName: ets-metrics
  rules:
  - host: ets-metrics.ucsd.edu
    http:
      paths:
      - path: {{.Values.gpu_stats_collector.ingress_path}}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-gpu-stats-collector
            port: 
              number: {{.Values.gpu_stats_collector.port}}

      - path: {{.Values.kube_state_metrics.ingress_path}}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-kube-state-metrics
            port: 
              number: {{.Values.kube_state_metrics.port}}
